from django.urls import path

from . import views


urlpatterns = [
    path("clients/", views.client_list, name="client_list"),
    path("clients/activity-log/", views.client_activity_log_list, name="client_activity_log_list"),
    path("clients/pending/", views.client_pending_list, name="client_pending_list"),
    path("clients/new/", views.client_create, name="client_create"),
    path("clients/import/", views.client_import, name="client_import"),
    path("clients/import/template/", views.client_import_template, name="client_import_template"),
    path("groups/", views.client_group_list, name="client_group_list"),
    path("groups/bulk-upload/", views.client_group_bulk_import, name="client_group_bulk_import"),
    path(
        "groups/bulk-upload/template/",
        views.client_group_bulk_import_template,
        name="client_group_bulk_import_template",
    ),
    path("groups/new/", views.client_group_create, name="client_group_create"),
    path("groups/bulk-delete/", views.client_group_bulk_delete, name="client_group_bulk_delete"),
    path("groups/<int:pk>/delete/", views.client_group_delete, name="client_group_delete"),
    path("groups/<int:pk>/", views.client_group_edit, name="client_group_edit"),
    path("clients/<str:client_id>/approve/", views.client_approve, name="client_approve"),
    path("clients/<str:client_id>/reject/", views.client_reject, name="client_reject"),
    path("portal-names/create/", views.portal_name_create_api, name="portal_name_create_api"),
    path("expense-categories/", views.expense_category_list, name="expense_category_list"),
    path("expense-categories/bulk-upload/", views.expense_category_bulk_import, name="expense_category_bulk_import"),
    path(
        "expense-categories/bulk-upload/template/",
        views.expense_category_bulk_import_template,
        name="expense_category_bulk_import_template",
    ),
    path("expense-categories/new/", views.expense_category_create, name="expense_category_create"),
    path("expense-categories/<int:pk>/delete/", views.expense_category_delete, name="expense_category_delete"),
    path("expense-categories/<int:pk>/", views.expense_category_edit, name="expense_category_edit"),
    path("portal-passwords/", views.portal_password_list, name="portal_password_list"),
    path("portal-passwords/bulk-upload/", views.portal_password_bulk_import, name="portal_password_bulk_import"),
    path(
        "portal-passwords/bulk-upload/template/",
        views.portal_password_bulk_import_template,
        name="portal_password_bulk_import_template",
    ),
    path("portal-passwords/new/", views.portal_password_create, name="portal_password_create"),
    path("portal-passwords/<int:pk>/delete/", views.portal_password_delete, name="portal_password_delete"),
    path("portal-passwords/<int:pk>/", views.portal_password_edit, name="portal_password_edit"),
    path("dsc/", views.dsc_list, name="dsc_list"),
    path("dsc/bulk-upload/", views.dsc_bulk_import, name="dsc_bulk_import"),
    path("dsc/bulk-upload/template/", views.dsc_bulk_import_template, name="dsc_bulk_import_template"),
    path("dsc/new/", views.dsc_create, name="dsc_create"),
    path("dsc/<int:pk>/delete/", views.dsc_delete, name="dsc_delete"),
    path("dsc/<int:pk>/", views.dsc_edit, name="dsc_edit"),
    path("dsc-in-out/", views.dsc_inout_list, name="dsc_inout_list"),
    path("dsc-in-out/<int:pk>/", views.dsc_inout_edit, name="dsc_inout_edit"),
    path("dsc-notifications/", views.dsc_notification_list, name="dsc_notification_list"),
    path("dsc-notifications/<int:pk>/read/", views.dsc_notification_mark_read, name="dsc_notification_mark_read"),
    path("clients/<str:client_id>/delete/", views.client_delete, name="client_delete"),
    path("clients/<str:client_id>/view/", views.client_detail, name="client_detail"),
    path("clients/<str:client_id>/edit/", views.client_edit, name="client_edit"),
    path("directors/", views.director_list, name="director_list"),
    path("directors/new/", views.director_create, name="director_create"),
    path("directors/<int:pk>/delete/", views.director_delete, name="director_delete"),
    path("directors/<int:pk>/", views.director_edit, name="director_edit"),
    path("directors/bulk-upload/", views.director_mapping_bulk_import, name="director_mapping_bulk_import"),
    path(
        "directors/bulk-upload/template/",
        views.director_mapping_bulk_import_template,
        name="director_mapping_bulk_import_template",
    ),
]

