# Generated by Django 5.1.6 on 2026-05-10 15:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_user_type_linked_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('client', 'Client')], db_index=True, default='employee', max_length=20, verbose_name='Type of user'),
        ),
    ]
