# Generated by Django 5.1.6 on 2026-05-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_branch_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch_access',
            field=models.CharField(blank=True, choices=[('', 'All branches'), ('Trivandrum', 'Trivandrum'), ('Nagercoil', 'Nagercoil')], default='', help_text='All branches, or restrict to Trivandrum or Nagercoil only.', max_length=32, verbose_name='Branch access'),
        ),
    ]
