# Generated by Django 5.1.6 on 2026-06-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='receive_dsc_expiry_notifications',
            field=models.BooleanField(default=False, help_text='Legacy flag; DSC expiry alerts use the view Client DSC permission instead.'),
        ),
    ]
