# Generated by Django 5.1.6 on 2026-05-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='masters_cli_client__71df69_idx',
            old_name='masters_cli_client__ccf7fa_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='masters_cli_pan_ee7374_idx',
            old_name='masters_cli_pan_43a7a0_idx',
        ),
    ]
