# Generated by Django 5.1.6 on 2026-05-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_client_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='branch',
            field=models.CharField(choices=[('Trivandrum', 'Trivandrum'), ('Nagercoil', 'Nagercoil')], default='Trivandrum', max_length=32),
        ),
    ]
