# Generated by Django 5.1.6 on 2026-05-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_directormapping_optional_appointed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('approve_client', 'Can approve client master records')]},
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='masters_cli_passpor_3722bc_idx',
            old_name='masters_cli_passport_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending approval')], db_index=True, default='approved', max_length=16),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Partnership', 'Partnership'), ('LLP', 'LLP'), ('Branch', 'Branch'), ('Private Limited', 'Private Limited'), ('Public Limited', 'Public Limited'), ('Nidhi Co', 'Nidhi Co'), ('FPO', 'FPO'), ('Trust', 'Trust'), ('Sec 8 Co', 'Sec 8 Co'), ('Society', 'Society'), ('Foreign Citizen', 'Foreign Citizen'), ('None', 'None')], max_length=32),
        ),
        migrations.AlterField(
            model_name='directormapping',
            name='director',
            field=models.ForeignKey(help_text='Select the director record from Client Master (Individual or Foreign Citizen with DIN).', on_delete=django.db.models.deletion.PROTECT, related_name='director_roles', to='masters.client'),
        ),
    ]
