# Generated by Django 5.1.6 on 2026-05-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_clientactivitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientactivitylog',
            new_name='masters_cli_client__420ef2_idx',
            old_name='masters_cli_client__a1b2c3_idx',
        ),
    ]
