# Generated by Django 5.1.6 on 2026-05-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_expensecategory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientdsc',
            new_name='masters_cli_expiry__b97558_idx',
            old_name='masters_cli_expiry__dsc01_idx',
        ),
        migrations.RenameIndex(
            model_name='clientdsc',
            new_name='masters_cli_client__9ac28a_idx',
            old_name='masters_cli_client__dsc02_idx',
        ),
        migrations.RenameIndex(
            model_name='clientportalcredential',
            new_name='masters_cli_portal__92d63c_idx',
            old_name='masters_cli_portal_fk_idx',
        ),
        migrations.RenameIndex(
            model_name='clientportalcredential',
            new_name='masters_cli_created_87749b_idx',
            old_name='masters_cli_created_4b91c0_idx',
        ),
        migrations.RenameIndex(
            model_name='dscnotification',
            new_name='masters_dsc_user_id_e486b1_idx',
            old_name='masters_dsc_user_rea_8a1f2c_idx',
        ),
    ]
