# Generated by Django 5.1.6 on 2026-05-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_client_type_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttype',
            name='pan_mandatory',
            field=models.BooleanField(default=True, help_text='When enabled, PAN must be entered on Client Master for this type.'),
        ),
    ]
