# Generated by Django 5.1.6 on 2026-05-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_grant_master_request_perms'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='masterrequest',
            new_name='masters_mas_assigne_eeae97_idx',
            old_name='masters_mas_assigne_8f4e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='masterrequest',
            new_name='masters_mas_request_097ac7_idx',
            old_name='masters_mas_request_91c3b1_idx',
        ),
        migrations.RenameIndex(
            model_name='masterrequestnotification',
            new_name='masters_mas_user_id_6081f8_idx',
            old_name='masters_mas_user_id_2a8f01_idx',
        ),
    ]
