# Generated by Django 5.1.6 on 2026-05-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_period_kind'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientdocument',
            new_name='documents_c_client__670b56_idx',
            old_name='documents_cl_client__a8f4c1_idx',
        ),
        migrations.RenameIndex(
            model_name='clientdocument',
            new_name='documents_c_client__528fda_idx',
            old_name='documents_cl_client__period_idx',
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='financial_year',
            field=models.CharField(blank=True, db_index=True, help_text='Legacy; Indian FY portion when applicable.', max_length=16),
        ),
        migrations.AlterField(
            model_name='documenttypetemplate',
            name='name_template',
            field=models.CharField(default='{document_type}-{client_name}', help_text='Placeholders: {document_type}, {client_name}, {pan}, {client_id}, {fy}, {month_label}, {quarter_label}, {half_label}, {period_label}', max_length=255),
        ),
    ]
