# Generated by Django 5.1.6 on 2026-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_sync_document_perms_to_client_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdocument',
            options={'ordering': ['-uploaded_at'], 'permissions': [('override_task_document_lock', 'Can change documents linked to a completed task')], 'verbose_name': 'client document', 'verbose_name_plural': 'client documents'},
        ),
        migrations.RenameIndex(
            model_name='clientdocument',
            new_name='documents_c_task_id_4ebf25_idx',
            old_name='documents_c_task_id_status_idx',
        ),
        migrations.AlterField(
            model_name='documenttypetemplate',
            name='name_template',
            field=models.CharField(default='{document_type}-{client_name}', help_text='Legacy field; uploads use automatic filenames from period kind.', max_length=255),
        ),
    ]
