# Generated by Django 5.1.6 on 2026-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_workflow_and_filters'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_client__1e828c_idx',
            old_name='tasks_task_client_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_verifie_0f89e4_idx',
            old_name='tasks_task_verifier_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_due_dat_3f7773_idx',
            old_name='tasks_task_due_status_idx',
        ),
        migrations.RenameIndex(
            model_name='taskactivity',
            new_name='tasks_taska_task_id_88cdfc_idx',
            old_name='tasks_activity_task_at_idx',
        ),
        migrations.RenameIndex(
            model_name='taskassignment',
            new_name='tasks_taska_user_id_ba7abe_idx',
            old_name='tasks_assign_user_at_idx',
        ),
        migrations.RenameIndex(
            model_name='taskmaster',
            new_name='tasks_taskm_is_acti_d88a15_idx',
            old_name='tasks_taskma_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='tasknotification',
            new_name='tasks_taskn_user_id_64d2ac_idx',
            old_name='tasks_notif_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='tasknotification',
            new_name='tasks_taskn_client__860de4_idx',
            old_name='tasks_notif_client_at_idx',
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assignee change'), ('status_change', 'Status change'), ('remark', 'Remark'), ('enrollment', 'Enrollment'), ('checklist', 'Checklist')], max_length=32),
        ),
    ]
