# Generated by Django 5.1.6 on 2026-05-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_status_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('assigned', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rework', 'Rework'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Users change'), ('status_change', 'Status change'), ('remark', 'Remark'), ('enrollment', 'Enrollment'), ('checklist', 'Checklist')], max_length=32),
        ),
    ]
