# Generated by Django 5.1.6 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_status_alter_taskactivity_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_assignment", "Awaiting assignment approval"),
                    ("assigned", "Pending"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rework", "Rework"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tasknotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("assignment_approval", "Assignment approval"),
                    ("verify", "Verification"),
                    ("rework", "Rework"),
                    ("approved", "Approved"),
                    ("recurring_fail", "Recurring failure"),
                    ("general", "General"),
                ],
                default="general",
                max_length=32,
            ),
        ),
    ]
