# Generated by Django 5.1.6 on 2026-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_document_rework_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_documen_ab22c1_idx',
            old_name='tasks_task_docchk_status_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='approved_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the verifier marks the task as verified.', null=True),
        ),
    ]
