# Generated by Django 5.1.6 on 2026-05-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_tasks_task_docchk_status_idx_tasks_task_documen_ab22c1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assignment'), ('status_change', 'Status change'), ('remark', 'Remark'), ('enrollment', 'Enrollment'), ('checklist', 'Checklist')], max_length=32),
        ),
    ]
