# Generated by Django 5.1.6 on 2026-05-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending_assignment', 'Awaiting user approval'), ('assigned', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('complete', 'Complete'), ('rework', 'Rework'), ('document_rework', 'Document rework'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20),
        ),
    ]
