# Generated by Django 5.1.6 on 2026-06-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_billable_fees_optional'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status_4a0a95_idx',
            old_name='tasks_task_status_idx',
        ),
    ]
