# Generated by Django 5.1.6 on 2026-06-12 06:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0009_receipt_tender_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdetail',
            name='expenses_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expenses billed on the client invoice (included in total).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
