# Generated by Django 5.1.6 on 2026-05-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirkyc', '0001_initial'),
        ('masters', '0016_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dir3kyc',
            name='director',
            field=models.ForeignKey(help_text='Individual or Foreign Citizen director with DIN from Client Master.', on_delete=django.db.models.deletion.PROTECT, related_name='dir3_kyc_records', to='masters.client'),
        ),
    ]
